name: Docker Image - Shipping Service

# This workflow created docker images, upload them in the DockerHub and run the containers for the BE
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

# Login with Docker Hub, so that docker images are store and available there instead of locally
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
# Build Docker Image  and upload it to Docker Hub
    - name: Build the Docker Image
      env:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        SERVICE_NAME: ${{vars.SERVICE_NAME}}
        TIME_STAMP: ${{ steps.date.outputs.date }}
      run: | 
        docker build . -f ./Dockerfile --tag $USERNAME/$SERVICE_NAME:$TIME_STAMP
        docker image push $USERNAME/$SERVICE_NAME:$TIME_STAMP
        docker run -d $USERNAME/$SERVICE_NAME:$TIME_STAMP
       

 
